"""
Parameter parsing tools.

Function names encode their parameter-kind sequence:
  pk  = positional-or-keyword
  pkd = positional-or-keyword with default
  po  = positional-only
  pod = positional-only with default
  ko  = keyword-only
  kod = keyword-only with default
  va  = *args
  vk  = **kwargs
"""

import inspect
import sys


# Annotated
def typed_empty(): ...
def typed_pk(x: int): ...
def typed_pkd(x: int = 1): ...
def typed_pk_pkd(x: int, y: int = 1): ...
def typed_po_pod(x: int, y: int = 1, /): ...
def typed_pk_pkd_ko(x: int, y: int = 1, *, z: int): ...
def typed_po_pod_pkd(x: int, y: int = 1, /, z: int = 2): ...
def typed_po_pod_ko(x: int, y: int = 1, /, *, z: int): ...
def typed_po_pod_kod(x: int, y: int = 1, /, *, z: int = 2): ...


# Args/Kwargs
def typed_va(*args: int): ...
def typed_vk(**kwargs: int): ...
def typed_va_vk(*args: int, **kwargs: int): ...
def typed_pk_va(x: int, *args: int): ...
def typed_pk_va_vk(x: int, *args: int, **kwargs: int): ...
def typed_pk_pkd_va(x: int, y: int = 1, *args: int): ...
def typed_va_ko(*args: int, z: int): ...
def typed_va_kod(*args: int, z: int = 2): ...
def typed_va_ko_vk(*args: int, z: int, **kwargs: int): ...
def typed_po_va(x: int, /, *args: int): ...
def typed_po_pod_va_ko_vk(x: int, y: int = 1, /, *args: int, z: int, **kwargs: int): ...
def typed_pk_ko_vk(x: int, *, z: int, **kwargs: int): ...
def typed_po_pod_ko_vk(x: int, y: int = 1, /, *, z: int, **kwargs: int): ...


# Not Annotated
def untyped_empty(): ...
def untyped_pk(x): ...
def untyped_pkd(x=1): ...
def untyped_pk_pkd(x, y=1): ...
def untyped_po_pod(x, y=1, /): ...
def untyped_pk_pkd_ko(x, y=1, *, z): ...
def untyped_po_pod_pkd(x, y=1, /, z=2): ...
def untyped_po_pod_ko(x, y=1, /, *, z): ...
def untyped_po_pod_kod(x, y=1, /, *, z=2): ...


# Args/Kwargs
def untyped_va(*args): ...
def untyped_vk(**kwargs): ...
def untyped_va_vk(*args, **kwargs): ...
def untyped_pk_va(x, *args): ...
def untyped_pk_va_vk(x, *args, **kwargs): ...
def untyped_pk_pkd_va(x, y=1, *args): ...
def untyped_va_ko(*args, z): ...
def untyped_va_kod(*args, z=2): ...
def untyped_va_ko_vk(*args, z, **kwargs): ...
def untyped_po_va(x, /, *args): ...
def untyped_po_pod_va_ko_vk(x, y=1, /, *args, z, **kwargs): ...
def untyped_pk_ko_vk(x, *, z, **kwargs): ...
def untyped_po_pod_ko_vk(x, y=1, /, *, z, **kwargs): ...


KIND_LABELS = {
    inspect.Parameter.POSITIONAL_ONLY: "POSITIONAL_ONLY",
    inspect.Parameter.POSITIONAL_OR_KEYWORD: "POSITIONAL_OR_KEYWORD",
    inspect.Parameter.VAR_POSITIONAL: "VAR_POSITIONAL",
    inspect.Parameter.KEYWORD_ONLY: "KEYWORD_ONLY",
    inspect.Parameter.VAR_KEYWORD: "VAR_KEYWORD",
}

for name, func in inspect.getmembers(sys.modules[__name__], inspect.isfunction):
    sig = inspect.signature(func)
    print(f"{name}{sig}")
    for param in sig.parameters.values():
        annotation = None if param.annotation is inspect.Parameter.empty else param.annotation
        has_default = param.default is not inspect.Parameter.empty
        default = repr(param.default) if has_default else "<no default>"
        print(
            f"  {param.name}: kind={KIND_LABELS[param.kind]} annotation={annotation} "
            f"has_default={has_default} default={default}"
        )
    print()
